reset;
model HW1-method1.mod;
data HW1.dat;

#Solve the minimization problem
option solver knitro;
solve;

#Write results in a file
printf {i in 0..4*K} "%10.5f %10.5f \n", p[i,0],p[i,1] > "HW1-model-1-position.txt";


reset;
model HW1-method2.mod;
data HW1.dat;

#Solve the minimization problem
option solver knitro;
solve;

#Write results in a file
printf {i in 0..4*K} "%10.5f %10.5f \n", p[i,0],p[i,1] > "HW1-model-2-position.txt";


